CREATE TABLE Directors
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(100) NOT NULL CHECK(Name != ''),
	CONSTRAINT PK_Directors PRIMARY KEY (Id)
)
GO

CREATE TABLE Genres
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(100) NOT NULL CHECK(Name != ''),
	CONSTRAINT PK_Genres PRIMARY KEY (Id)
)
GO

CREATE TABLE Languages
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(100) NOT NULL CHECK(Name != ''),
	CONSTRAINT PK_Languages PRIMARY KEY (Id)
)
GO

CREATE TABLE Films
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(100) NOT NULL CHECK(Name != ''),
	DirectorId INT NOT NULL,
	GenreId INT NOT NULL,
	Year INT NOT NULL CHECK(Year <= YEAR(GETDATE())),
	Duration INT NOT NULL,
	LanguageId INT NOT NULL,
	AgeLimit INT NOT NULL CHECK(AgeLimit >= 0),
	Rating FLOAT NOT NULL CHECK(Rating BETWEEN 0 AND 12),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	CONSTRAINT PK_Films PRIMARY KEY (Id),
	CONSTRAINT FK_Films_Directors FOREIGN KEY (DirectorId) REFERENCES Directors (Id),
	CONSTRAINT FK_Films_Genres FOREIGN KEY (GenreId) REFERENCES Genres (Id),
	CONSTRAINT FK_Films_Languages FOREIGN KEY (LanguageId) REFERENCES Languages (Id)
)
GO

CREATE TABLE Halls
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(50) NOT NULL CHECK(Name != ''),
	Capacity INT NOT NULL CHECK(Capacity >= 0),
	CountRows INT NOT NULL CHECK(CountRows >= 0),
	CONSTRAINT PK_Halls PRIMARY KEY (Id)
)
GO

CREATE TABLE Sessions
(
	Id INT NOT NULL IDENTITY,
	Date DATETIME NOT NULL,
	FilmId INT NOT NULL,
	HallId INT NOT NULL,
	CONSTRAINT PK_Sessions PRIMARY KEY (Id),
	CONSTRAINT FK_Sessions_Films FOREIGN KEY (FilmId) REFERENCES Films (Id),
	CONSTRAINT FK_Sessions_Halls FOREIGN KEY (HallId) REFERENCES Halls (Id)
)
GO

CREATE TABLE Sectors
(
	Id INT NOT NULL IDENTITY,
	Name NVARCHAR(50) NOT NULL CHECK(Name != ''),
	CONSTRAINT PK_Sectors PRIMARY KEY (Id)
)
GO

CREATE TABLE HallSectors
(
	Id INT NOT NULL IDENTITY,
	SectorId INT NOT NULL,
	HallId INT NOT NULL,
	StartRow INT NOT NULL CHECK(StartRow >= 0),
	EndRow INT NOT NULL CHECK(EndRow >= 0),
	CONSTRAINT PK_HallSectors PRIMARY KEY (Id),
	CONSTRAINT FK_HallSectors_Sectors FOREIGN KEY (SectorId) REFERENCES Sectors (Id),
	CONSTRAINT FK_HallSectors_Halls FOREIGN KEY (HallId) REFERENCES Halls (Id)
)
GO

CREATE TABLE Places
(
	Id INT NOT NULL IDENTITY,
	HallSectorId INT NOT NULL,
	Row INT NOT NULL CHECK(Row >= 0),
	Number INT NOT NULL CHECK(Number >= 0),
	CONSTRAINT PK_Places PRIMARY KEY (Id),
	CONSTRAINT FK_Places_HallSectors FOREIGN KEY (HallSectorId) REFERENCES HallSectors (Id)
)
GO

CREATE TABLE Tickets
(
	Id INT NOT NULL IDENTITY,
	SessionId INT NOT NULL,
	PlaceId INT NOT NULL,
	DateOfSale DATETIME NOT NULL CHECK(DateOfSale <= GETDATE()),
	Price MONEY NOT NULL CHECK(Price >= 0.0),
	CONSTRAINT PK_Tickets PRIMARY KEY (Id),
	CONSTRAINT FK_Tickets_Sessions FOREIGN KEY (SessionId) REFERENCES Sessions (Id),
	CONSTRAINT FK_Tickets_Places FOREIGN KEY (PlaceId) REFERENCES Places (Id)
)
GO
